services:
  postgres:
    image: postgres:16
    container_name: zabbix-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-trunk
    container_name: zabbix-server
    restart: always
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "10051:10051"
    depends_on:
      - postgres

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-trunk
    container_name: zabbix-frontend
    restart: always
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PHP_TZ: Europe/Moscow
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-trunk
    container_name: zabbix-agent
    restart: always
    environment:
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "10050:10050"

volumes:
  postgres-data:
